import imgOne from '../assets/profile1.webp'
import imgTwo from '../assets/profile2.webp'
import imgThree from '../assets/profile3.webp'
import imgFour from '../assets/profile4.webp'

export const helpData = [
    {
        id: 1,
        name: 'John Doe',
        title: 'Need help with coding',
        description: 'Can someone help me with my javascript assignment?',
        fullDetails: ' I have a project due next week and I am struggling with some concepts. I need assistance in understanding callbacks and promises. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgOne,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
        location: 'Online',
        status: 'open'
    },
    {
        id: 2,
        name: 'John Doe',
        title: 'Need help getting groceries',
        description: 'Can someone help me get groceries?',
        fullDetails: 'I am unable to go out due to the pandemic and I need some help getting groceries. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgTwo,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
        location: 'Online',
        status: 'open'
    },
    {
        id: 3,
        name: 'John Doe',
        title: 'Need help learning guitar',
        description: 'Can someone help me with learning how to play the guitar?',
        fullDetails: 'I have been trying to learn it for a while but I am unable to understand some concepts. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgOne,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
        location: 'Online',
        status: 'open'
    },
    {
        id: 4,
        name: 'John Doe',
        title: 'Need help with cleaning my house',
        description: 'Can someone help me clean?',
        fullDetails: 'I am unable to go out due to the pandemic and I need some help cleaning my house. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgThree,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
        location: 'Online',
        status: 'open'
    },
    {
        id: 5,
        name: 'John Doe',
        title: 'Need help shopping for groceries',
        description: 'Can someone help me with shopping for groceries?',
        fullDetails: 'I am unable to go out due to the pandemic and I need some help shopping for groceries. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgOne,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
        location: 'Online',
        status: 'open'
    },
    {
        id: 6,
        name: 'John Doe',
        title: 'Need help with coding',
        description: 'Can someone help me with my javascript assignment?',
        fullDetails: ' I have a project due next week and I am struggling with some concepts. I need assistance in understanding callbacks and promises. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgOne,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
        location: 'Online',
        status: 'open'
    },
    {
        id: 7,
        name: 'John Doe',
        title: 'Need help with coding',
        description: 'Can someone help me with my javascript assignment?',
        fullDetails: ' I have a project due next week and I am struggling with some concepts. I need assistance in understanding callbacks and promises. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgFour,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
        location: 'Online',
        status: 'open'
    },
    {
        id: 8,
        name: 'John Doe',
        title: 'Need help with coding',
        description: 'Can someone help me with my javascript assignment?',
        fullDetails: ' I have a project due next week and I am struggling with some concepts. I need assistance in understanding callbacks and promises. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgTwo,
        reward: '20',
        date: '2021-08-08',
    }
]

export const offerHelpData = [
    {
        id: 1,
        name: 'John Doe',
        title: 'Can teach python',
        description: 'I can help someone with python over ther weekend',
        fullDetails: 'I can help someone with python over ther weekend. I have been working with python for 5 years and I am very comfortable with it. I would really appreciate it if someone could help me out.',
        category: 'coding',
        image: imgOne,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
    },
    {
        id: 2,
        name: 'John Doe',
        title: 'Can help with gardening',
        description: 'I can help someone with gardening this weekend',
        fullDetails: 'I can help someone with gardening this weekend. I love gardening and I am very comfortable with it. I would really appreciate it if someone could help me out.',
        category: 'gardening',
        image: imgFour,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
    },
    {
        id: 3,
        name: 'John Doe',
        title: 'I can go out with your dog',
        description: 'I can help someone with walking their dog this weekend',
        fullDetails: 'I can help someone with walking their dog this weekend. I love dogs and I am very comfortable with it. I would really appreciate it if someone could help me out.',
        category: 'gardening',
        image: imgTwo,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
    },
    {
        id: 4,
        name: 'John Doe',
        title: 'Can help with gardening',
        description: 'I can help someone with gardening this weekend',
        fullDetails: 'I can help someone with gardening this weekend. I love gardening and I am very comfortable with it. I would really appreciate it if someone could help me out.',
        category: 'gardening',
        image: imgThree,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
    },
    {
        id: 5,
        name: 'John Doe',
        title: 'Can help with gardening',
        description: 'I can help someone with gardening this weekend',
        fullDetails: 'I can help someone with gardening this weekend. I love gardening and I am very comfortable with it. I would really appreciate it if someone could help me out.',
        category: 'gardening',
        image: imgOne,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
    },
    {
        id: 6,
        name: 'John Doe',
        title: 'Can help with gardening',
        description: 'I can help someone with gardening this weekend',
        fullDetails: 'I can help someone with gardening this weekend. I love gardening and I am very comfortable with it. I would really appreciate it if someone could help me out.',
        category: 'gardening',
        image: imgFour,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
    },
    {
        id: 7,
        name: 'John Doe',
        title: 'Can help with gardening',
        description: 'I can help someone with gardening this weekend',
        fullDetails: 'I can help someone with gardening this weekend. I love gardening and I am very comfortable with it. I would really appreciate it if someone could help me out.',
        category: 'gardening',
        image: imgTwo,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
    },
    {
        id: 8,
        name: 'John Doe',
        title: 'Can help with gardening',
        description: 'I can help someone with gardening this weekend',
        fullDetails: 'I can help someone with gardening this weekend. I love gardening and I am very comfortable with it. I would really appreciate it if someone could help me out.',
        category: 'gardening',
        image: imgThree,
        reward: '20',
        date: '2021-08-08',
        time: '10:00',
    }

]
